version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: checkin_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123456
      MYSQL_DATABASE: checkin_app
      MYSQL_USER: checkin_user
      MYSQL_PASSWORD: checkin123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - mysql_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot123456"]
      timeout: 20s
      retries: 10
      interval: 30s
      start_period: 60s

volumes:
  mysql_data:
    driver: local

networks:
  mysql_network:
    driver: bridge 